### ISSUE TITLE
Here are some suggestions to improve this code with best practices:

### ISSUE THREAD

**Issue by Alejandroq12** [VelzckC0D3/Portfolio_v2#10]
Hello, Alejandro. Excellent job. Your project is very responsive and professional.

[Optiona] suggestions:
-- Use descriptive comments to explain complex logic

Great job, continue that way.
![GreatDayGIF](https://user-images.githubusercontent.com/95459740/224338360-281d8de6-40eb-4b8c-b800-207adec2ef69.gif)

**Comment by VelzckC0D3** [comment]
Thank you!

**Comment by Metaverse-Nabeel** [comment]
I really enjoyed the demo. The quality of code is amazing. 
I have nothing to say other than "Great Job!"
